#!/usr/bin/env bash
# Generate the scratch project used to test `/kmp-to-kmpilot` (Phase 6, Stage B).
#
# Stage B's input is an ADOPTED KMP project whose features do not follow KMPilot's
# rules. This script produces exactly that, in one command and with no network:
#
#   1. delegates the buildable baseline to `make-adopt-target.sh` (an ordinary
#      Compose Multiplatform app: `app/` + `shared/`, its own catalog, its own
#      package prefix — nothing KMPilot about it),
#   2. layers on nine deliberately non-conforming modules,
#   3. commits, then adopts in place via `install.sh --adopt` with
#      `KMPILOT_SOURCE_DIR` pointed at this checkout — so the fixture carries a real
#      `.kmpilot.json` written by the real installer, not a hand-faked one, and the
#      whole thing runs offline.
#
# Usage:
#   scripts/make-nonconforming-project.sh [target-dir] [--force] [--no-adopt]
#
#   target-dir  default: ~/KMPProjects/nonconforming-target
#   --force     regenerate over an existing fixture (only ever deletes a directory
#               carrying the .nonconforming-fixture marker)
#   --no-adopt  stop before adopting — the `unadopted` role variant, which must be
#               told to run `install.sh --adopt` rather than migrated
#
# What each added module exists to exercise, one discovery path apiece:
#
#   :core:model        plain value types                → common.app proposal
#   :core:netcall      Ktor client + @Serializable DTOs → data.app proposal, and
#                                                         consumed by TWO features,
#                                                         so the DRY corollary applies
#   :core:widgets      @Composable                      → designsystem.app proposal
#   :core:androidutil  android.content.Context in
#                      commonMain                       → UNHOISTABLE refusal, and it
#                                                         blocks the feature using it
#   :feature:notes     owns a repository another
#                      feature imports                  → shared code inside a feature
#   :feature:portable  Material3, `_state.value =`,
#                      English literals, no di/, no
#                      UiModel, no desktop target,
#                      cross-feature import             → the migratable case
#   :feature:legacy    Retrofit + Hilt + LiveData +
#                      Context in commonMain            → Android-locked refusal
#   :feature:headless  no @Composable anywhere          → no-entry-point refusal
#   :oldscreen         a feature never moved under
#                      feature/                         → outside-feature/ note
#
# Plus, project-wide: two version catalogs (the host's `libs` and adopt's
# `kmpilotLibs`) → the catalog-split note.
#
# BUILDABILITY. Steps 1-2 of Stage B are pure static analysis — discovery and the
# refusal matrix run without Gradle, a JDK or the Android SDK, in about a second.
# The baseline `app/` + `shared/` modules inherited from make-adopt-target.sh build;
# the refusal modules deliberately import libraries that are not in the catalog
# (Retrofit, Hilt), because their whole purpose is to be refused and never compiled.
# Making the migratable half compile end-to-end is the rewrite steps' job, not this
# script's.

set -euo pipefail

TARGET="${HOME}/KMPProjects/nonconforming-target"
FORCE=no
ADOPT=yes
for arg in "$@"; do
    case "$arg" in
        --force) FORCE=yes ;;
        --no-adopt) ADOPT=no ;;
        -h|--help) sed -n '2,60p' "$0"; exit 0 ;;
        -*) echo "Error: unknown argument '$arg'" >&2; exit 1 ;;
        *)  TARGET="$arg" ;;
    esac
done

PKG="com.acme.notes"
PKG_PATH="${PKG//.//}"
MARKER=".nonconforming-fixture"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KMPILOT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

command -v git >/dev/null 2>&1 || { echo "Error: git is required" >&2; exit 1; }

if [[ -e "$TARGET" ]]; then
    if [[ "$FORCE" != "yes" ]]; then
        echo "Error: '$TARGET' already exists. Pass --force to regenerate it." >&2
        exit 1
    fi
    # Only ever delete something this script created.
    if [[ ! -f "$TARGET/$MARKER" ]]; then
        echo "Error: '$TARGET' exists but has no $MARKER marker — refusing to delete it." >&2
        exit 1
    fi
    echo "→ Removing existing fixture at $TARGET"
    rm -rf "$TARGET"
fi

# ── 1. the ordinary, buildable KMP baseline ─────────────────────────────────
echo "→ Generating the KMP baseline via make-adopt-target.sh"
bash "$SCRIPT_DIR/make-adopt-target.sh" "$TARGET" >/dev/null
cd "$TARGET"

cat > "$MARKER" <<'EOF'
Generated by KMPilot's scripts/make-nonconforming-project.sh — a disposable test
fixture for /kmp-to-kmpilot (Phase 6, Stage B). Safe to delete. Regenerate with
--force.
EOF

# ── 2. register the non-conforming modules ──────────────────────────────────
# Appended rather than rewritten so the baseline's pluginManagement and catalog
# wiring stay exactly as make-adopt-target.sh wrote them.
cat >> settings.gradle.kts <<'EOF'

// ── Added by make-nonconforming-project.sh ──────────────────────────────────
include(":core:model")
include(":core:netcall")
include(":core:widgets")
include(":core:androidutil")
include(":feature:notes")
include(":feature:portable")
include(":feature:legacy")
include(":feature:headless")
include(":oldscreen")
// A commented-out include must never be read as a module:
// include(":feature:ghost")
EOF

# A KMP library module in the host's own style: android + ios, no desktop, reading
# the host catalog. Every added module is generated from this one shape.
write_module_gradle() {
    local dir="$1" namespace="$2" extra_deps="${3:-}"
    cat > "$dir/build.gradle.kts" <<EOF
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKmpLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

kotlin {
    android {
        namespace = "${namespace}"
        compileSdk =
            libs.versions.android.compileSdk
                .get()
                .toInt()
        minSdk =
            libs.versions.android.minSdk
                .get()
                .toInt()
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget -> iosTarget.binaries.framework { baseName = "${namespace##*.}" } }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.lifecycle.viewmodel)
            implementation(libs.koin.core)
${extra_deps}
        }
    }
}
EOF
}

kt() { # kt <path> — write stdin to a Kotlin file, creating parents
    mkdir -p "$(dirname "$1")"
    cat > "$1"
}

# ── :core:model — plain value types → common.app ────────────────────────────
mkdir -p "core/model"
write_module_gradle "core/model" "${PKG}.model"
kt "core/model/src/commonMain/kotlin/${PKG_PATH}/model/Note.kt" <<EOF
package ${PKG}.model

data class Note(
    val id: String,
    val title: String,
    val body: String,
)

data class Money(val amount: Long, val currency: String)
EOF

# ── :core:netcall — Ktor + wire DTOs → data.app, two feature consumers ──────
mkdir -p "core/netcall"
write_module_gradle "core/netcall" "${PKG}.netcall" "            implementation(libs.ktor.core)
            implementation(libs.ktor.json)
            implementation(libs.kotlinx.serialization.json)"
kt "core/netcall/src/commonMain/kotlin/${PKG_PATH}/netcall/NotesApi.kt" <<EOF
package ${PKG}.netcall

import io.ktor.client.HttpClient
import io.ktor.client.request.get

class NotesApi(private val client: HttpClient) {
    suspend fun fetch(): Result<List<NoteDto>> = runCatching { client.get("/notes").body() }
}
EOF
kt "core/netcall/src/commonMain/kotlin/${PKG_PATH}/netcall/NoteDto.kt" <<EOF
package ${PKG}.netcall

import kotlinx.serialization.Serializable

@Serializable
data class NoteDto(
    val id: String,
    val title: String,
    val body: String,
)
EOF

# ── :core:widgets — composables → designsystem.app ──────────────────────────
mkdir -p "core/widgets"
write_module_gradle "core/widgets" "${PKG}.widgets"
kt "core/widgets/src/commonMain/kotlin/${PKG_PATH}/widgets/NoteBadge.kt" <<EOF
package ${PKG}.widgets

import androidx.compose.material3.Text
import androidx.compose.runtime.Composable

@Composable
fun NoteBadge(label: String) {
    Text(text = label)
}
EOF

# ── :core:androidutil — Android framework type in commonMain → UNHOISTABLE ──
mkdir -p "core/androidutil"
write_module_gradle "core/androidutil" "${PKG}.androidutil"
kt "core/androidutil/src/commonMain/kotlin/${PKG_PATH}/androidutil/Toaster.kt" <<EOF
package ${PKG}.androidutil

import android.content.Context
import android.widget.Toast

// Android-only, in commonMain: nothing that depends on this can migrate until it
// moves behind a DataSource with per-platform actuals (Rule 14).
class Toaster(private val context: Context) {
    fun show(message: String) {
        Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
    }
}
EOF

# ── :feature:notes — owns a repository another feature imports ──────────────
mkdir -p "feature/notes"
write_module_gradle "feature/notes" "${PKG}.notes" "            implementation(project(\":core:model\"))
            implementation(project(\":core:netcall\"))
            implementation(project(\":core:widgets\"))"
kt "feature/notes/src/commonMain/kotlin/${PKG_PATH}/notes/NotesRepository.kt" <<EOF
package ${PKG}.notes

import ${PKG}.model.Note
import ${PKG}.netcall.NotesApi

// Shared code that happens to live inside a feature — the placement question only
// project-scoped migration can answer.
class NotesRepository(private val api: NotesApi) {
    suspend fun all(): Result<List<Note>> = runCatching { emptyList() }
}
EOF
kt "feature/notes/src/commonMain/kotlin/${PKG_PATH}/notes/NotesScreen.kt" <<EOF
package ${PKG}.notes

import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import ${PKG}.widgets.NoteBadge

@Composable
fun NotesScreen() {
    Text(text = "Notes")
    NoteBadge(label = "unread")
}
EOF

# ── :feature:portable — the migratable non-conforming case ──────────────────
# Rule bait, deliberately: R5 Material3, R3 `_state.value =`, R12 English literals,
# R8 no di/ package, R11b no *UiModel, R9 a UseCase layer, and no desktop target.
mkdir -p "feature/portable"
write_module_gradle "feature/portable" "${PKG}.portable" "            implementation(project(\":core:model\"))
            implementation(project(\":core:netcall\"))
            implementation(project(\":core:androidutil\"))
            implementation(project(\":feature:notes\"))"
kt "feature/portable/src/commonMain/kotlin/${PKG_PATH}/portable/PortableScreen.kt" <<EOF
package ${PKG}.portable

import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable

@Composable
fun PortableScreen(viewModel: PortableViewModel) {
    Scaffold { padding ->
        Text(text = "Your notes")
        Button(onClick = { viewModel.reload() }) {
            Text(text = "Reload")
        }
        CircularProgressIndicator()
    }
}
EOF
kt "feature/portable/src/commonMain/kotlin/${PKG_PATH}/portable/PortableViewModel.kt" <<EOF
package ${PKG}.portable

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import ${PKG}.androidutil.Toaster
import ${PKG}.notes.NotesRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.launch

data class PortableState(
    val loading: Boolean = false,
    val error: String? = null,
)

class PortableViewModel(
    private val repository: NotesRepository,
    private val loadNotesUseCase: LoadNotesUseCase,
    private val toaster: Toaster,
) : ViewModel() {
    private val _state = MutableStateFlow(PortableState())

    fun reload() {
        viewModelScope.launch {
            // Rule 3: assignment instead of setState.
            _state.value = _state.value.copy(loading = true)
            val result = loadNotesUseCase()
            _state.value = _state.value.copy(loading = false, error = result.exceptionOrNull()?.message)
        }
    }
}
EOF
kt "feature/portable/src/commonMain/kotlin/${PKG_PATH}/portable/LoadNotesUseCase.kt" <<EOF
package ${PKG}.portable

import ${PKG}.model.Note
import ${PKG}.notes.NotesRepository

// Rule 9: there is no UseCase layer in KMPilot — ViewModels call repositories.
class LoadNotesUseCase(private val repository: NotesRepository) {
    suspend operator fun invoke(): Result<List<Note>> = repository.all()
}
EOF

# ── :feature:legacy — Android-locked → refusal ──────────────────────────────
# Imports Retrofit and Hilt without declaring them: this module exists to be
# refused, never compiled. See BUILDABILITY in the header.
mkdir -p "feature/legacy"
write_module_gradle "feature/legacy" "${PKG}.legacy"
kt "feature/legacy/src/commonMain/kotlin/${PKG_PATH}/legacy/LegacyScreen.kt" <<EOF
package ${PKG}.legacy

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import dagger.hilt.android.lifecycle.HiltViewModel
import javax.inject.Inject
import retrofit2.http.GET

@Composable
fun LegacyScreen() = Unit

@HiltViewModel
class LegacyViewModel @Inject constructor(
    private val context: Context,
) {
    val notes: LiveData<String> = MutableLiveData()
}

interface LegacyService {
    @GET("notes")
    suspend fun notes(): String
}
EOF
kt "feature/legacy/src/commonMain/kotlin/${PKG_PATH}/legacy/LegacyNotes.kt" <<EOF
package ${PKG}.legacy

// A commented-out Android import must never fabricate refusal evidence:
// import androidx.fragment.app.Fragment
/* import androidx.appcompat.app.AppCompatActivity */

class LegacyNotes
EOF

# ── :feature:headless — no composable at all → refusal ──────────────────────
mkdir -p "feature/headless"
write_module_gradle "feature/headless" "${PKG}.headless"
kt "feature/headless/src/commonMain/kotlin/${PKG_PATH}/headless/SyncWorker.kt" <<EOF
package ${PKG}.headless

// No @Composable anywhere: there is no screen to migrate.
class SyncWorker {
    fun sync(): Int = 0
}
EOF

# ── :oldscreen — a feature that never moved under feature/ ──────────────────
mkdir -p "oldscreen"
write_module_gradle "oldscreen" "${PKG}.oldscreen" "            implementation(project(\":core:model\"))
            implementation(project(\":core:netcall\"))"
kt "oldscreen/src/commonMain/kotlin/${PKG_PATH}/oldscreen/OldScreen.kt" <<EOF
package ${PKG}.oldscreen

import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import ${PKG}.netcall.NotesApi

@Composable
fun OldScreen(api: NotesApi) {
    Text(text = "Legacy list")
}
EOF

# The app module depends on the two features it actually shows — Integration Point 4
# in the host's own shape, which discovery must NOT mistake for shared code.
python3 - "$PKG" <<'PY'
import re, sys
from pathlib import Path

pkg = sys.argv[1]
path = Path("shared/build.gradle.kts")
text = path.read_text()
added = f'''            implementation(project(":feature:portable"))
            implementation(project(":feature:notes"))
'''
text = text.replace("        commonMain.dependencies {\n",
                    "        commonMain.dependencies {\n" + added, 1)
path.write_text(text)

nav = Path(f"shared/src/commonMain/kotlin/{pkg.replace('.', '/')}/NonconformingNav.kt")
nav.parent.mkdir(parents=True, exist_ok=True)
nav.write_text(f'''package {pkg}

import androidx.compose.runtime.Composable
import {pkg}.notes.NotesScreen
import {pkg}.portable.PortableScreen

// The app shell reaching into features is Integration Point 4, not shared code.
@Composable
fun NonconformingNav() {{
    NotesScreen()
}}
''')
PY

# ── 3. commit, then adopt ───────────────────────────────────────────────────
# Adopt refuses a dirty tree, so the fixture is committed first. (Migration itself
# supports a dirty tree — that is a separate matrix variant, not a fixture concern.)
git add -A
git -c user.email=fixture@local -c user.name=fixture commit --quiet \
    -m "AcmeNotes: features and shared code, pre-KMPilot conventions"

if [[ "$ADOPT" == "yes" ]]; then
    echo "→ Adopting in place from this checkout (offline)"
    KMPILOT_SOURCE_DIR="$KMPILOT_ROOT" \
    KMPILOT_ASSUME_YES=1 \
    KMPILOT_NONINTERACTIVE=1 \
        bash "$KMPILOT_ROOT/install.sh" --adopt --app-module=shared >/dev/null \
        || { echo "Error: install.sh --adopt failed. Re-run it by hand to see why:" >&2
             echo "  cd $TARGET && KMPILOT_SOURCE_DIR=$KMPILOT_ROOT bash $KMPILOT_ROOT/install.sh --adopt --app-module=shared" >&2
             exit 1; }
    git add -A
    git -c user.email=fixture@local -c user.name=fixture commit --quiet \
        -m "Adopt KMPilot"
    echo "✓ Adopted — .kmpilot.json written by the real installer"
else
    echo "✓ Left unadopted (--no-adopt): the 'run install.sh --adopt first' variant"
fi

echo "✓ Fixture ready at $TARGET"
echo
echo "Next:"
echo "  python3 $KMPILOT_ROOT/.claude/skills/_shared/kmpilot_discover.py --root $TARGET"
echo "  bash $KMPILOT_ROOT/scripts/migrate-matrix.sh"
